In [37]:
import pandas as pd 

df = pd.read_csv("../../data/exploded.csv")
df.head()

/var/folders/sp/zrg_wt6n4hs4l4nz5y1b6zs00000gn/T/ipykernel_55346/2568867549.py:3: DtypeWarning: Columns (0: grant_recipient_project_title, 1: project_description, 2: expected_duration, 3: gender_dimension, 4: subsector, 5: row_id, 6: Sector, 7: channel_name, 8: channel_reported_name) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../../data/exploded.csv")

,year,organization_name,region,country,usd_disbursements_defl,grant_recipient_project_title,project_description,expected_duration,type_of_flow,Donor_country,...,usd_commitment_defl,channel_code,channel_name,channel_reported_name,environment,biodiversity,desertification,nutrition,region_macro,mission_desc
0,2022,True Colours Trust,Eastern Africa,Malawi,0.041862,Towards the costs of updating lockable cupboar...,Towards the costs of lockable cupboards in Dis...,2022-2023,Cross-border,United Kingdom,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Africa,"Achieve By 2030, reduce by one third premature..."
1,2020,True Colours Trust,Eastern Africa,Malawi,0.054969,Towards the purchase of PPE during the COVID19...,Towards the purchase of PPE during the COVID19...,2020-2020,Cross-border,United Kingdom,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Africa,"Achieve By 2030, end the epidemics of AIDS, tu..."
2,2021,True Colours Trust,Eastern Africa,Malawi,0.366887,Towards Phase 5 of integrating palliative care...,Towards Phase 5 of integrating palliative care...,2021-2024,Cross-border,United Kingdom,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Africa,"Achieve Achieve universal health coverage, inc..."
3,2021,True Colours Trust,Eastern Africa,Malawi,0.366887,Towards Phase 5 of integrating palliative care...,Towards Phase 5 of integrating palliative care...,2021-2024,Cross-border,United Kingdom,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Africa,"Achieve Achieve universal health coverage, inc..."
4,2020,True Colours Trust,Eastern Africa,Malawi,0.016170,Towards the production of films on Palliative ...,Towards the production of films on Palliative ...,2020-2021,Cross-border,United Kingdom,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Africa,"Achieve By 2030, reduce by one third premature..."

In [3]:
df.columns

Index(['year', 'organization_name', 'region', 'country',
       'usd_disbursements_defl', 'grant_recipient_project_title',
       'project_description', 'expected_duration', 'type_of_flow',
       'Donor_country', 'financial_instrument', 'modality_of_giving',
       'gender_dimension', 'additional_info', 'gender_marker',
       'climate_change_mitigation', 'climate_change_adaptation', 'subsector',
       'sdg_focus', 'row_id', 'subsector_description', 'Sector',
       'sector_description', 'usd_commitment_defl', 'channel_code',
       'channel_name', 'channel_reported_name', 'environment', 'biodiversity',
       'desertification', 'nutrition', 'region_macro', 'mission_desc'],
      dtype='str')

In [38]:
test = df.drop(['project_description', 'expected_duration', 'type_of_flow', 'financial_instrument', 'modality_of_giving',
       'gender_dimension', 'additional_info', 'gender_marker',
       'climate_change_mitigation', 'climate_change_adaptation', 'subsector', 'row_id', 'subsector_description', 'Sector',
       'sector_description', 'usd_commitment_defl', 'channel_code',
       'channel_name', 'channel_reported_name', 'environment', 'biodiversity',
       'desertification', 'nutrition', 'region_macro'], axis=1)
test.head()
test.shape

(90875, 9)

In [40]:
test['mission_desc'] = test['mission_desc'].str.replace('.', '', regex=False)
test.head()

,year,organization_name,region,country,usd_disbursements_defl,grant_recipient_project_title,Donor_country,sdg_focus,mission_desc
0,2022,True Colours Trust,Eastern Africa,Malawi,0.041862,Towards the costs of updating lockable cupboar...,United Kingdom,3.4,"Achieve By 2030, reduce by one third premature..."
1,2020,True Colours Trust,Eastern Africa,Malawi,0.054969,Towards the purchase of PPE during the COVID19...,United Kingdom,3.3,"Achieve By 2030, end the epidemics of AIDS, tu..."
2,2021,True Colours Trust,Eastern Africa,Malawi,0.366887,Towards Phase 5 of integrating palliative care...,United Kingdom,3.8,"Achieve Achieve universal health coverage, inc..."
3,2021,True Colours Trust,Eastern Africa,Malawi,0.366887,Towards Phase 5 of integrating palliative care...,United Kingdom,3.8,"Achieve Achieve universal health coverage, inc..."
4,2020,True Colours Trust,Eastern Africa,Malawi,0.016170,Towards the production of films on Palliative ...,United Kingdom,3.4,"Achieve By 2030, reduce by one third premature..."

In [30]:
df_old = pd.read_csv("../../data/OECD-Dataset.csv")
df_old.shape

/var/folders/sp/zrg_wt6n4hs4l4nz5y1b6zs00000gn/T/ipykernel_55346/3196058025.py:1: DtypeWarning: Columns (0: year, 1: grant_recipient_project_title, 2: expected_duration, 3: financial_instrument, 4: modality_of_giving, 5: gender_dimension, 6: additional_info, 7: subsector, 8: Sector, 9: channel_name, 10: channel_reported_name) have mixed types. Specify dtype option on import or set low_memory=False.
  df_old = pd.read_csv("../../data/OECD-Dataset.csv")

(116561, 32)

In [41]:
test.to_csv("../../data/dropped_rows.csv", index=False)